namespace: moment-dev

replicaCount: 1

image:
  repository: 611058323802.dkr.ecr.ap-northeast-3.amazonaws.com/moment-dev-ai-service
  tag: dev-placeholder
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ai-service
  annotations: {}

config:
  AWS_REGION: ap-northeast-3
  ENVIRONMENT: dev

secretRefs: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
