namespace: moment-dev

replicaCount: 1

image:
  repository: 611058323802.dkr.ecr.ap-northeast-3.amazonaws.com/moment-dev-ai-service
  tag: dev-19a2a3d
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: moment-dev-ai-service-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::611058323802:role/moment-dev-ai-service-irsa-role"

config:
  ENVIRONMENT: dev
  RUNTIME_PROFILE: dev
  SERVER_PORT: "8000"
  AWS_REGION: ap-northeast-3
  LOG_LEVEL: DEBUG
  MODEL_NAME: default
  OPENSEARCH_HOST: vpc-moment-dev-opensearch-hdseoos3ibawg6xwwlaa4hff3u.ap-northeast-3.es.amazonaws.com
  BACKEND_API_URL: "http://backend-api:8080"

secretRefs:
  - envName: OPENAI_API_KEY
    secretName: moment-dev-ai-service-secret
    secretKey: openai-api-key

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

nodeSelector:
  workload: core
  capacity: on-demand

tolerations: []

affinity: {}
