apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-api-dev-secret
  namespace: moment-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: backend-api
    app.kubernetes.io/part-of: moment
    app.kubernetes.io/managed-by: argocd
    environment: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: moment-dev-aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: moment-dev-backend-api-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
  data:
    - secretKey: db-username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: moment/dev/backend-api
        property: db-username
    - secretKey: db-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: moment/dev/backend-api
        property: db-password
    - secretKey: jwt-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: moment/dev/backend-api
        property: jwt-secret
    - secretKey: toss-secret-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: moment/dev/backend-api
        property: toss-secret-key
    - secretKey: toss-client-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: moment/dev/backend-api
        property: toss-client-key
    - secretKey: toss-success-url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: moment/dev/backend-api
        property: toss-success-url
    - secretKey: toss-fail-url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: moment/dev/backend-api
        property: toss-fail-url
    - secretKey: kakao-client-id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: moment/dev/backend-api
        property: kakao-client-id
    - secretKey: kakao-redirect-uri
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: moment/dev/backend-api
        property: kakao-redirect-uri
    - secretKey: public-data-data-go-kr-service-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: moment/dev/backend-api
        property: public-data-data-go-kr-service-key
