apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: batch-job-dev-secret
  namespace: moment-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: batch-job
    app.kubernetes.io/part-of: moment
    app.kubernetes.io/managed-by: argocd
    environment: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: moment-dev-aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: moment-dev-batch-job-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
  data:
    - secretKey: db-username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: moment/dev/batch-job
        property: db-username
    - secretKey: db-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: moment/dev/batch-job
        property: db-password
    - secretKey: public-data-api-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: moment/dev/batch-job
        property: public-data-api-key
    - secretKey: jwt-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: moment/dev/batch-job
        property: jwt-secret
