apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-api-prod-secret
  namespace: moment-prod
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: backend-api
    app.kubernetes.io/part-of: moment
    app.kubernetes.io/managed-by: argocd
    environment: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: moment-prod-aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: moment-prod-backend-api-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: db-username
      remoteRef:
        key: rds!db-da6fa9ec-26b3-4b31-be42-7d1e9599bf26
        property: username
    - secretKey: db-password
      remoteRef:
        key: rds!db-da6fa9ec-26b3-4b31-be42-7d1e9599bf26
        property: password
    - secretKey: jwt-secret
      remoteRef:
        key: moment/prod/backend-api
        property: jwt-secret
    - secretKey: toss-secret
      remoteRef:
        key: moment/prod/backend-api
        property: toss-secret
