apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-api-prod-secret
  namespace: moment-prod
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: backend-api
    app.kubernetes.io/part-of: moment
    app.kubernetes.io/managed-by: argocd
    environment: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: moment-prod-aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: moment-prod-backend-api-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: db-username
      remoteRef:
        key: rds!db-b5c6d98d-5694-4e0f-b853-6ea1435415ce
        property: username
    - secretKey: db-password
      remoteRef:
        key: rds!db-b5c6d98d-5694-4e0f-b853-6ea1435415ce
        property: password
    - secretKey: jwt-secret
      remoteRef:
        key: moment/prod/backend-api
        property: jwt-secret
    - secretKey: toss-secret-key
      remoteRef:
        key: moment/prod/backend-api
        property: toss-secret-key
    - secretKey: toss-client-key
      remoteRef:
        key: moment/prod/backend-api
        property: toss-client-key
    - secretKey: toss-success-url
      remoteRef:
        key: moment/prod/backend-api
        property: toss-success-url
    - secretKey: toss-fail-url
      remoteRef:
        key: moment/prod/backend-api
        property: toss-fail-url
    - secretKey: kakao-client-secret
      remoteRef:
        key: moment/prod/backend-api
        property: kakao-client-secret
    - secretKey: kakao-client-id
      remoteRef:
        key: moment/prod/backend-api
        property: kakao-client-id
    - secretKey: kakao-redirect-uri
      remoteRef:
        key: moment/prod/backend-api
        property: kakao-redirect-uri
    - secretKey: public-data-data-go-kr-service-key
      remoteRef:
        key: moment/prod/backend-api
        property: public-data-data-go-kr-service-key
