apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: batch-job-prod-secret
  namespace: moment-prod
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: batch-job
    app.kubernetes.io/part-of: moment
    app.kubernetes.io/managed-by: argocd
    environment: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: moment-prod-aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: moment-prod-batch-job-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
  data:
    - secretKey: db-username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: rds!db-b5c6d98d-5694-4e0f-b853-6ea1435415ce
        property: username
    - secretKey: db-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: rds!db-b5c6d98d-5694-4e0f-b853-6ea1435415ce
        property: password
    - secretKey: public-data-api-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: moment/prod/batch-job
        property: public-data-api-key
    - secretKey: jwt-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: moment/prod/batch-job
        property: jwt-secret
