apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: moment-prod-aws-secretsmanager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: moment
    app.kubernetes.io/managed-by: argocd
    environment: prod
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-3
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
