namespace: ""
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
  name: ""
  annotations: {}
schedule: "0 * * * *"
concurrencyPolicy: Forbid
successfulJobsHistoryLimit: 3
failedJobsHistoryLimit: 1
backoffLimit: 3
restartPolicy: OnFailure
args: []
config: {}
secretRefs: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
