apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: moment-prod-slack-alert-webhook
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: moment-slack-alert-webhook
    app.kubernetes.io/part-of: moment
    app.kubernetes.io/managed-by: argocd
    environment: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: moment-prod-aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: moment-prod-slack-alert-webhook
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
  data:
    - secretKey: url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        key: moment/prod/monitoring/slack-alert-webhook
        property: url
