namespace: "moment"

replicaCount: 2

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""
  annotations: {}

config: {}
secretRefs: []

startupProbe: {}
readinessProbe: {}
livenessProbe: {}

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: null
  behavior: {}

# core On-Demand 노드에 배치
nodeSelector:
  workload: core

tolerations: []

# 멀티AZ 분산 (core 노드 2개: 3a, 3c)
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - backend-api
          topologyKey: topology.kubernetes.io/zone

ingress:
  enabled: true
  className: alb
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

# Rolling Update 전략
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

# PodDisruptionBudget
pdb:
  enabled: true
  minAvailable: 1
