namespace: ""
replicaCount: 1
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
  name: ""
  annotations: {}
config: {}
secretRefs: []
startupProbe: {}
readinessProbe: {}
livenessProbe: {}
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: null
  behavior: {}
nodeSelector: {}
tolerations: []
affinity: {}
ingress:
  enabled: false
  className: alb
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
