apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-policy-prod
  namespace: argocd
spec:
  project: moment-prod
  source:
    repoURL: https://github.com/Team-msp-architect-2026/msp-team04-infra
    targetRevision: develop
    path: gitops/charts/network-policy
    helm:
      valueFiles:
        - ../../../values/prod/network-policy-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: moment-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
