apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-delivery-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: secret-delivery
    app.kubernetes.io/part-of: moment
    app.kubernetes.io/managed-by: argocd
    environment: dev
spec:
  project: moment-dev
  source:
    repoURL: https://github.com/Team-msp-architect-2026/msp-team04-infra.git
    targetRevision: develop
    path: gitops/apps/dev/secret-delivery
  destination:
    server: https://kubernetes.default.svc
    namespace: moment-dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
