namespace: ""
replicaCount: 1
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
  name: ""
  annotations: {}
config: {}
secretRefs: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
