apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/part-of: moment
    app.kubernetes.io/managed-by: argocd
    environment: prod
spec:
  project: aws-load-balancer-controller-prod
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 3.4.0
    helm:
      releaseName: aws-load-balancer-controller
      values: |
        clusterName: moment-prod-eks-cluster
        region: ap-northeast-3
        vpcId: vpc-02bcd9d35dd3152e2

        replicaCount: 2

        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::611058323802:role/moment-prod-aws-load-balancer-controller-irsa-role"

        nodeSelector:
          workload: ops
          capacity: on-demand

        tolerations:
          - key: workload
            operator: Equal
            value: ops
            effect: NoSchedule

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: aws-load-balancer-tls
      namespace: kube-system
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: aws-load-balancer-webhook
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: aws-load-balancer-webhook
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
