apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-api-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: backend-api
    app.kubernetes.io/part-of: moment
    app.kubernetes.io/managed-by: argocd
    environment: prod
spec:
  project: moment-prod
  source:
    repoURL: https://github.com/Team-msp-architect-2026/msp-team04-infra.git
    targetRevision: develop
    path: gitops/charts/backend-api
    helm:
      valueFiles:
        - ../../values/prod/backend-api-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: moment-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
