apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: moment
    app.kubernetes.io/managed-by: argocd
    environment: prod
spec:
  project: external-secrets-prod
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 2.5.0
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: false
        serviceAccount:
          create: true
          name: external-secrets
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::611058323802:role/moment-prod-external-secrets-irsa-role"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - ApplyOutOfSyncOnly=true
