namespace: moment-prod

replicaCount: 2

image:
  repository: 611058323802.dkr.ecr.ap-northeast-3.amazonaws.com/moment-prod-ai-service
  tag: prod-33aa58d
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: moment-prod-ai-service-sa
  annotations: {}
  # TODO: prod ai-service 전용 IRSA Role 생성 후 아래 형태로 변경
  # annotations:
  #   eks.amazonaws.com/role-arn: "arn:aws:iam::611058323802:role/moment-prod-ai-service-irsa-role"

config:
  ENVIRONMENT: prod
  AWS_REGION: ap-northeast-3
  LOG_LEVEL: INFO
  OPENSEARCH_HOST: vpc-moment-prod-opensearch-2trht5bolkacngjunc6lsbibuq.ap-northeast-3.es.amazonaws.com
  BACKEND_API_URL: "http://backend-api:8080"

secretRefs:
  - envName: OPENAI_API_KEY
    secretName: moment-prod-ai-service-secret
    secretKey: openai-api-key

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

nodeSelector:
  workload: ai
  capacity: spot

tolerations:
  - key: workload
    operator: Equal
    value: ai
    effect: NoSchedule
  - key: capacity
    operator: Equal
    value: spot
    effect: NoSchedule

affinity: {}
