namespace: moment-prod

replicaCount: 2

image:
  repository: 611058323802.dkr.ecr.ap-northeast-3.amazonaws.com/moment-prod-backend-api
  tag: prod-placeholder
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: backend-api
  annotations: {}

config:
  AWS_REGION: ap-northeast-3
  ENVIRONMENT: prod

secretRefs: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
